load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "eventbus",
    srcs = [
        "event_bus.cpp",
    ],
    hdrs = [
        "event.h",
        "event_bus.h",
    ],
    visibility = ["//visibility:public"],
)
