
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files (x86)/CMake/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:26 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files (x86)/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files (x86)/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files (x86)/CMake/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:26 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Microsoft (R)-Build-Engine, Version 15.9.21+g9802d43bc3 für .NET Framework
      Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.
      
      Der Buildvorgang wurde am 01.10.2023 17:38:20 gestartet.
      Projekt "D:\\Simon\\Programming\\Habitify\\cmake_out\\CMakeFiles\\3.27.6\\CompilerIdC\\CompilerIdC.vcxproj" auf Knoten "1" (Standardziele).
      PrepareForBuild:
        Das Verzeichnis "Debug\\" wird erstellt.
        Das Verzeichnis "Debug\\CompilerIdC.tlog\\" wird erstellt.
      InitializeBuildStatus:
        "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" wird erstellt, da "AlwaysCreate" angegeben wurde.
      ClCompile:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\CL.exe /c /nologo /W0 /WX- /diagnostics:classic /Od /Oy- /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc141.pdb" /Gd /TC /analyze- /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X86 /SAFESEH Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> D:\\Simon\\Programming\\Habitify\\cmake_out\\CMakeFiles\\3.27.6\\CompilerIdC\\.\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\Hostx86\\x86\\cl.exe
      FinalizeBuildStatus:
        Die Datei "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" wird gelöscht.
        Aktualisieren des Timestamps von "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      Die Erstellung von Projekt "D:\\Simon\\Programming\\Habitify\\cmake_out\\CMakeFiles\\3.27.6\\CompilerIdC\\CompilerIdC.vcxproj" ist abgeschlossen (Standardziele).
      
      Der Buildvorgang wurde erfolgreich ausgeführt.
          0 Warnung(en)
          0 Fehler
      
      Verstrichene Zeit 00:00:02.67
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        D:/Simon/Programming/Habitify/cmake_out/CMakeFiles/3.27.6/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files (x86)/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files (x86)/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files (x86)/CMake/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:26 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Microsoft (R)-Build-Engine, Version 15.9.21+g9802d43bc3 für .NET Framework
      Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.
      
      Der Buildvorgang wurde am 01.10.2023 17:38:23 gestartet.
      Projekt "D:\\Simon\\Programming\\Habitify\\cmake_out\\CMakeFiles\\3.27.6\\CompilerIdCXX\\CompilerIdCXX.vcxproj" auf Knoten "1" (Standardziele).
      PrepareForBuild:
        Das Verzeichnis "Debug\\" wird erstellt.
        Das Verzeichnis "Debug\\CompilerIdCXX.tlog\\" wird erstellt.
      InitializeBuildStatus:
        "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" wird erstellt, da "AlwaysCreate" angegeben wurde.
      ClCompile:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\CL.exe /c /nologo /W0 /WX- /diagnostics:classic /Od /Oy- /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X86 /SAFESEH Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> D:\\Simon\\Programming\\Habitify\\cmake_out\\CMakeFiles\\3.27.6\\CompilerIdCXX\\.\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\Hostx86\\x86\\cl.exe
      FinalizeBuildStatus:
        Die Datei "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" wird gelöscht.
        Aktualisieren des Timestamps von "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      Die Erstellung von Projekt "D:\\Simon\\Programming\\Habitify\\cmake_out\\CMakeFiles\\3.27.6\\CompilerIdCXX\\CompilerIdCXX.vcxproj" ist abgeschlossen (Standardziele).
      
      Der Buildvorgang wurde erfolgreich ausgeführt.
          0 Warnung(en)
          0 Fehler
      
      Verstrichene Zeit 00:00:03.29
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        D:/Simon/Programming/Habitify/cmake_out/CMakeFiles/3.27.6/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files (x86)/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files (x86)/CMake/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:26 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "D:/Simon/Programming/Habitify/cmake_out/CMakeFiles/CMakeScratch/TryCompile-08gago"
      binary: "D:/Simon/Programming/Habitify/cmake_out/CMakeFiles/CMakeScratch/TryCompile-08gago"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
      CMAKE_C_FLAGS_DEBUG: "/MDd /Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:X86"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'D:/Simon/Programming/Habitify/cmake_out/CMakeFiles/CMakeScratch/TryCompile-08gago'
        
        Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin/MSBuild.exe" cmTC_57af8.vcxproj /p:Configuration=Debug /p:Platform=Win32 /p:VisualStudioVersion=15.0 /v:n
        Microsoft (R)-Build-Engine, Version 15.9.21+g9802d43bc3 für .NET Framework
        Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.
        
        Der Buildvorgang wurde am 01.10.2023 17:38:27 gestartet.
        Projekt "D:\\Simon\\Programming\\Habitify\\cmake_out\\CMakeFiles\\CMakeScratch\\TryCompile-08gago\\cmTC_57af8.vcxproj" auf Knoten "1" (Standardziele).
        PrepareForBuild:
          Das Verzeichnis "cmTC_57af8.dir\\Debug\\" wird erstellt.
          Das Verzeichnis "D:\\Simon\\Programming\\Habitify\\cmake_out\\CMakeFiles\\CMakeScratch\\TryCompile-08gago\\Debug\\" wird erstellt.
          Das Verzeichnis "cmTC_57af8.dir\\Debug\\cmTC_57af8.tlog\\" wird erstellt.
        InitializeBuildStatus:
          "cmTC_57af8.dir\\Debug\\cmTC_57af8.tlog\\unsuccessfulbuild" wird erstellt, da "AlwaysCreate" angegeben wurde.
        ClCompile:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\CL.exe /c /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /Oy- /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_57af8.dir\\Debug\\\\" /Fd"cmTC_57af8.dir\\Debug\\vc141.pdb" /Gd /TC /analyze- /errorReport:queue "C:\\Program Files (x86)\\CMake\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
          Microsoft (R) C/C++-Optimierungscompiler Version 19.16.27045 für x86
          Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.
          
          cl /c /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /Oy- /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_57af8.dir\\Debug\\\\" /Fd"cmTC_57af8.dir\\Debug\\vc141.pdb" /Gd /TC /analyze- /errorReport:queue "C:\\Program Files (x86)\\CMake\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
          CMakeCCompilerABI.c
          
        Link:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\link.exe /ERRORREPORT:QUEUE /OUT:"D:\\Simon\\Programming\\Habitify\\cmake_out\\CMakeFiles\\CMakeScratch\\TryCompile-08gago\\Debug\\cmTC_57af8.exe" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"D:/Simon/Programming/Habitify/cmake_out/CMakeFiles/CMakeScratch/TryCompile-08gago/Debug/cmTC_57af8.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/Simon/Programming/Habitify/cmake_out/CMakeFiles/CMakeScratch/TryCompile-08gago/Debug/cmTC_57af8.lib" /MACHINE:X86 /SAFESEH  /machine:X86 cmTC_57af8.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_57af8.vcxproj -> D:\\Simon\\Programming\\Habitify\\cmake_out\\CMakeFiles\\CMakeScratch\\TryCompile-08gago\\Debug\\cmTC_57af8.exe
        FinalizeBuildStatus:
          Die Datei "cmTC_57af8.dir\\Debug\\cmTC_57af8.tlog\\unsuccessfulbuild" wird gelöscht.
          Aktualisieren des Timestamps von "cmTC_57af8.dir\\Debug\\cmTC_57af8.tlog\\cmTC_57af8.lastbuildstate".
        Die Erstellung von Projekt "D:\\Simon\\Programming\\Habitify\\cmake_out\\CMakeFiles\\CMakeScratch\\TryCompile-08gago\\cmTC_57af8.vcxproj" ist abgeschlossen (Standardziele).
        
        Der Buildvorgang wurde erfolgreich ausgeführt.
            0 Warnung(en)
            0 Fehler
        
        Verstrichene Zeit 00:00:01.58
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files (x86)/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files (x86)/CMake/share/cmake-3.27/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:26 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "D:/Simon/Programming/Habitify/cmake_out/CMakeFiles/CMakeScratch/TryCompile-uvz3wd"
      binary: "D:/Simon/Programming/Habitify/cmake_out/CMakeFiles/CMakeScratch/TryCompile-uvz3wd"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/MDd /Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:X86"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'D:/Simon/Programming/Habitify/cmake_out/CMakeFiles/CMakeScratch/TryCompile-uvz3wd'
        
        Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin/MSBuild.exe" cmTC_28e6b.vcxproj /p:Configuration=Debug /p:Platform=Win32 /p:VisualStudioVersion=15.0 /v:n
        Microsoft (R)-Build-Engine, Version 15.9.21+g9802d43bc3 für .NET Framework
        Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.
        
        Der Buildvorgang wurde am 01.10.2023 17:38:29 gestartet.
        Projekt "D:\\Simon\\Programming\\Habitify\\cmake_out\\CMakeFiles\\CMakeScratch\\TryCompile-uvz3wd\\cmTC_28e6b.vcxproj" auf Knoten "1" (Standardziele).
        PrepareForBuild:
          Das Verzeichnis "cmTC_28e6b.dir\\Debug\\" wird erstellt.
          Das Verzeichnis "D:\\Simon\\Programming\\Habitify\\cmake_out\\CMakeFiles\\CMakeScratch\\TryCompile-uvz3wd\\Debug\\" wird erstellt.
          Das Verzeichnis "cmTC_28e6b.dir\\Debug\\cmTC_28e6b.tlog\\" wird erstellt.
        InitializeBuildStatus:
          "cmTC_28e6b.dir\\Debug\\cmTC_28e6b.tlog\\unsuccessfulbuild" wird erstellt, da "AlwaysCreate" angegeben wurde.
        ClCompile:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\CL.exe /c /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /Oy- /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /std:c++latest /Fo"cmTC_28e6b.dir\\Debug\\\\" /Fd"cmTC_28e6b.dir\\Debug\\vc141.pdb" /Gd /TP /analyze- /errorReport:queue "C:\\Program Files (x86)\\CMake\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
          Microsoft (R) C/C++-Optimierungscompiler Version 19.16.27045 für x86
          Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.
          
          cl /c /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /Oy- /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /std:c++latest /Fo"cmTC_28e6b.dir\\Debug\\\\" /Fd"cmTC_28e6b.dir\\Debug\\vc141.pdb" /Gd /TP /analyze- /errorReport:queue "C:\\Program Files (x86)\\CMake\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
          CMakeCXXCompilerABI.cpp
          
        Link:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\link.exe /ERRORREPORT:QUEUE /OUT:"D:\\Simon\\Programming\\Habitify\\cmake_out\\CMakeFiles\\CMakeScratch\\TryCompile-uvz3wd\\Debug\\cmTC_28e6b.exe" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"D:/Simon/Programming/Habitify/cmake_out/CMakeFiles/CMakeScratch/TryCompile-uvz3wd/Debug/cmTC_28e6b.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/Simon/Programming/Habitify/cmake_out/CMakeFiles/CMakeScratch/TryCompile-uvz3wd/Debug/cmTC_28e6b.lib" /MACHINE:X86 /SAFESEH  /machine:X86 cmTC_28e6b.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_28e6b.vcxproj -> D:\\Simon\\Programming\\Habitify\\cmake_out\\CMakeFiles\\CMakeScratch\\TryCompile-uvz3wd\\Debug\\cmTC_28e6b.exe
        FinalizeBuildStatus:
          Die Datei "cmTC_28e6b.dir\\Debug\\cmTC_28e6b.tlog\\unsuccessfulbuild" wird gelöscht.
          Aktualisieren des Timestamps von "cmTC_28e6b.dir\\Debug\\cmTC_28e6b.tlog\\cmTC_28e6b.lastbuildstate".
        Die Erstellung von Projekt "D:\\Simon\\Programming\\Habitify\\cmake_out\\CMakeFiles\\CMakeScratch\\TryCompile-uvz3wd\\cmTC_28e6b.vcxproj" ist abgeschlossen (Standardziele).
        
        Der Buildvorgang wurde erfolgreich ausgeführt.
            0 Warnung(en)
            0 Fehler
        
        Verstrichene Zeit 00:00:01.68
        
      exitCode: 0
...
