name: CI

on: [push, pull_request]

jobs:
  test:
    # virtual environments: https://github.com/actions/virtual-environments
    runs-on: ubuntu-20.04

    steps:
      # Caches and restores the bazelisk download directory, the bazel build directory.
      - name: Cache bazel
        uses: actions/cache@v2
        env:
          cache-name: bazel-cache
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-development

      # Checks-out your repository under $GITHUB_WORKSPACE, which is the CWD for
      # the rest of the steps
      - uses: actions/checkout@v2

      - name: Check if third_party/ was already cached
        id: check_cache
        uses: actions/cache@v2
        with:
          path: third_party/
          key: ${{ runner.os }}-third_party_cache-${{ github.ref }}

      - if: steps.check_cache.outputs.cache-hit != 'true'
        name: Install submodules
        run:  git submodule update --init --recursive

      - name: Cache third_party/ directory
        id: cache-third-party
        uses: actions/cache@v2
        with:
          path: third_party/
          key: ${{ runner.os }}-third_party_cache-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-third_party_cache-
        
      - name: Install OpenGL libraries on Ubuntu
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libgl1-mesa-dev

      # build
      - name: Build the code
        run: bazel build :Habitify
      # - name: Run the test
      #   run: bazel test //...
