name: CI

on: [push, pull_request]

jobs:
  test:
    # virtual environments: https://github.com/actions/virtual-environments
    runs-on: ubuntu-20.04

    steps:
      # Caches and restores the bazelisk download directory, the bazel build directory.
      - name: Cache bazel
        uses: actions/cache@v3
        env:
          cache-name: bazel-cache
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-development

      # Checks-out your repository under $GITHUB_WORKSPACE, which is the CWD for
      # the rest of the steps
      - uses: actions/checkout@v3

      - name: Cache third_party
        id: check_cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/third_party
          key: ${{ runner.os }}-third-party-cache-${{ github.ref }}

      - if: steps.check_cache.outputs.cache-hit != 'true'
        name: Init Submodules
        run: |
          git submodule update --init --recursive
        
      - name: Install OpenGL libraries on Ubuntu
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libgl1-mesa-dev

      # build
      - name: Build the code
        run: bazel build :Habitify
      # - name: Run the test
      #   run: bazel test //...
