name: CI

on: [push, pull_request]

jobs:
  test:
    # virtual environments: https://github.com/actions/virtual-environments
    runs-on: ubuntu-20.04

    steps:
      # Caches and restores the bazelisk download directory, the bazel build directory.
      - name: Cache bazel
        uses: actions/cache@v2
        env:
          cache-name: bazel-cache
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-development

      # Checks-out your repository under $GITHUB_WORKSPACE, which is the CWD for
      # the rest of the steps
      - uses: actions/checkout@v2

      - name: Check if submodules were already cached
        id: check_cache
        run: echo "::set-output name=cached::$(test -d third_party/)"

      - if: steps.check_cache.outputs.cached == 'false'
        name: Install submodules
        run: |
          git submodule update --init --recursive
        continue-on-error: true

      - name: Cache Submodules
        id: submodule-cache
        uses: actions/cache@v2
        env:
          cache-name: submodules-cache
        with:
          path: |
            third_party
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-development
        
      - name: Install OpenGL libraries on Ubuntu
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libgl1-mesa-dev

      # build
      - name: Build the code
        run: bazel build :Habitify
      # - name: Run the test
      #   run: bazel test //...